.TH "C:/IPCA/PI/Aulas/Aula2/ola.c" 3 "Thu Oct 29 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/IPCA/PI/Aulas/Aula2/ola.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
